---
- name: 'Instala pacotes de dependencia do sistema operacional'
  apt:
    update_cache: yes
    cache_valid_time: 3600 #1 hora
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - mysql-server-5.7
    - python3-mysqldb

- name: 'Cria banco de dados MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: "{{ wp_db_user }}"
    state: present
  become: yes

- name: 'Cria o usuário do MySQL'
  mysql_user:
    login_user: "{{ wp_db_user }}"
    name: "{{ wp_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - 'localhost'
    - "{{ wp_host_ip }}"
  become: yes

- name: 'Substituir arquivo de configuração do MySQL'
  copy:
    src: 'files/mysqld.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
  become: yes
  notify:
    - restart mysql